# Generated by Django 4.2.7 on 2023-11-16 15:00

import caching.base
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Switch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True, unique=True)),
                ("ipaddress", models.CharField(max_length=100, unique=True)),
                (
                    "switch_type",
                    models.IntegerField(
                        choices=[
                            (0, "UNKNOWN"),
                            (3, "FREESWITCH"),
                            (4, "ASTERISK"),
                            (5, "YATE"),
                            (6, "KAMAILIO"),
                            (7, "OPENSIPS"),
                            (8, "SIPWISE"),
                            (9, "VERAZ"),
                        ],
                        default=3,
                        max_length=100,
                    ),
                ),
                ("key_uuid", models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                "verbose_name": "switch",
                "verbose_name_plural": "switches",
                "db_table": "voip_switch",
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
    ]
